apiVersion: apps/v1
kind: Deployment
metadata:
  name: nani-app
  labels:
    app: nani-app
spec:
  replicas: 2  # Adjust as needed
  selector:
    matchLabels:
      app: nani-app
  template:
    metadata:
      labels:
        app: nani-app
    spec:
      containers:
      - name: nani-app
        image: kennethreitz/httpbin:test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
