apiVersion: v1
kind: Service
metadata:
  name: nani-service
  labels:
    app: nani-app
spec:
  type: LoadBalancer  # Use NodePort if needed
  selector:
    app: nani-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
